import Sidebar from '@/components/molecules/sidenavbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Topnavbar from '@/components/molecules/topnavbar'
import { ThemeProvider } from '../material-tailwind'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body className={`${inter.className} w-full h-screen`}>
        <div className='flex h-full w-full'>
          <Sidebar />
          <div className='w-full'>
            <div className='w-full'>
            <Topnavbar />
            </div>
            <div className='h-max overflow-x-hidden w-full overflow-y-auto p-5'>
              {children}
            </div>
          </div>
        </div>
      </body>
      </ThemeProvider>
    </html>
  )
}
