import Sidebar from '@/components/sidenavbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Topnavbar from '@/components/topnavbar'
import { ThemeProvider } from '../material-tailwind'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body className={inter.className}>
        <div className='flex'>
          <Sidebar />
          <div className='w-full'>
            <Topnavbar />
            <div className='z-10 relative h-max overflow-x-hidden w-max overflow-y-auto left-[16%] top-[81px]'>
            {children}
            </div>
          </div>
        </div>
      </body>
      </ThemeProvider>
    </html>
  )
}
